name: Git Workshop Demo

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'chore/**' 
env:
  SERVER_IP: '127.0.0.1'
  COMPANY_NAME: 'NTPLC'
  REPO_NAME: ${{github.repository}}

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      PHONE: '0999998'
    environment: development
    steps:
      - run: echo "Hello ${{github.actor}} ${{env.PHONE}}"
      - run: echo "Hello ${{env.COMPANY_NAME}}"
      - run: echo ${{env.REPO_NAME}}
      - run: echo ${{vars.APP_NAME}}
      - run: echo ${{secrets.API_KEY}}
  job-2:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Hello ${{env.COMPANY_NAME}}"
      - run: echo ${{env.SERVER_IP}}
      - run: echo ${{vars.SERVER_IP_PRODUCTION}}